### ISSUE TITLE
Update publications manifest to match latest data model

### ISSUE THREAD

**Issue by vpchung** [mc2-center/pubmed-crawler#6]
The new format should match this schema:

<img width="348" alt="publications-schema" src="https://user-images.githubusercontent.com/9377970/187562295-3322d286-d0f7-4345-a98d-fa572ad36b8e.png">

**Comment by vpchung** [comment]
@brynnz22 I just wanted to make sure that with the new manifest format, capturing the dataset links are no longer needed?  Just the dataset IDs?

**Comment by brynnz22** [comment]
@vpchung yes, the dataset links are no longer needed in the publications manifest. Just the dataset alias, which I think is the same thing as what we used to call the dataset IDs.
